# Generated by Django 4.0.4 on 2022-04-20 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wws', to=settings.AUTH_USER_MODEL),
        ),
    ]
