# Generated by Django 4.0.4 on 2022-04-18 17:10

from django.db import migrations, models
import drive.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='file အမည်', max_length=255)),
                ('file', models.FileField(upload_to=drive.models.file_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
