# Generated by Django 4.0.4 on 2022-04-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_file_share_ays_file_share_bge_file_share_bgw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
